# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: navi.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'navi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnavi.proto\x12\x04navi\"\x1d\n\rSearchRequest\x12\x0c\n\x04term\x18\x01 \x01(\t\"-\n\x0bSearchReply\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\"1\n\x0f\x44ownloadRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\"\x1f\n\rDownloadReply\x12\x0e\n\x06result\x18\x01 \x01(\x03\x32|\n\nDownloader\x12\x34\n\x06Search\x12\x13.navi.SearchRequest\x1a\x11.navi.SearchReply\"\x00\x30\x01\x12\x38\n\x08\x44ownload\x12\x15.navi.DownloadRequest\x1a\x13.navi.DownloadReply\"\x00\x42(\n\x13\x63om.aeroponics.naviB\tNaviProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'navi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.aeroponics.naviB\tNaviProtoP\001\242\002\003HLW'
  _globals['_SEARCHREQUEST']._serialized_start=20
  _globals['_SEARCHREQUEST']._serialized_end=49
  _globals['_SEARCHREPLY']._serialized_start=51
  _globals['_SEARCHREPLY']._serialized_end=96
  _globals['_DOWNLOADREQUEST']._serialized_start=98
  _globals['_DOWNLOADREQUEST']._serialized_end=147
  _globals['_DOWNLOADREPLY']._serialized_start=149
  _globals['_DOWNLOADREPLY']._serialized_end=180
  _globals['_DOWNLOADER']._serialized_start=182
  _globals['_DOWNLOADER']._serialized_end=306
# @@protoc_insertion_point(module_scope)
