# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nicotine.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'nicotine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enicotine.proto\x12\x06\x65xtras\"\x1d\n\rSearchRequest\x12\x0c\n\x04term\x18\x01 \x01(\t\"0\n\x0eSearchResponse\x12\x1e\n\x08response\x18\x01 \x01(\x0b\x32\x0c.extras.File\"0\n\x0f\x44ownloadRequest\x12\x1d\n\x07request\x18\x01 \x01(\x0b\x32\x0c.extras.File\"*\n\x04\x46ile\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x66ilepath\x18\x02 \x01(\t\"v\n\x10\x44ownloadResponse\x12(\n\x06status\x18\x01 \x01(\x0b\x32\x16.extras.DownloadStatusH\x00\x12,\n\x08progress\x18\x02 \x01(\x0b\x32\x18.extras.DownloadProgressH\x00\x42\n\n\x08response\"\x91\x01\n\x0e\x44ownloadStatus\x12-\n\x06status\x18\x05 \x01(\x0e\x32\x1d.extras.DownloadStatus.Status\"P\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06QUEUED\x10\x01\x12\x0f\n\x0b\x44OWNLOADING\x10\x02\x12\r\n\tCOMPLETED\x10\x03\x12\r\n\tCANCELLED\x10\x04\"$\n\x10\x44ownloadProgress\x12\x10\n\x08progress\x18\x01 \x01(\x05\x32\x8c\x01\n\nDownloader\x12;\n\x06Search\x12\x15.extras.SearchRequest\x1a\x16.extras.SearchResponse\"\x00\x30\x01\x12\x41\n\x08\x44ownload\x12\x17.extras.DownloadRequest\x1a\x18.extras.DownloadResponse\"\x00\x30\x01\x42+Z#github.com/bh90210/navidrome/extras\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nicotine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/bh90210/navidrome/extras\242\002\003HLW'
  _globals['_SEARCHREQUEST']._serialized_start=26
  _globals['_SEARCHREQUEST']._serialized_end=55
  _globals['_SEARCHRESPONSE']._serialized_start=57
  _globals['_SEARCHRESPONSE']._serialized_end=105
  _globals['_DOWNLOADREQUEST']._serialized_start=107
  _globals['_DOWNLOADREQUEST']._serialized_end=155
  _globals['_FILE']._serialized_start=157
  _globals['_FILE']._serialized_end=199
  _globals['_DOWNLOADRESPONSE']._serialized_start=201
  _globals['_DOWNLOADRESPONSE']._serialized_end=319
  _globals['_DOWNLOADSTATUS']._serialized_start=322
  _globals['_DOWNLOADSTATUS']._serialized_end=467
  _globals['_DOWNLOADSTATUS_STATUS']._serialized_start=387
  _globals['_DOWNLOADSTATUS_STATUS']._serialized_end=467
  _globals['_DOWNLOADPROGRESS']._serialized_start=469
  _globals['_DOWNLOADPROGRESS']._serialized_end=505
  _globals['_DOWNLOADER']._serialized_start=508
  _globals['_DOWNLOADER']._serialized_end=648
# @@protoc_insertion_point(module_scope)
